### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by backelj** [vscentrum/status-page#4]
Hi all

I wanted to add a new incident, but when I try to render it, I get:

```
parsing file 'incidents/kul_20220621.yml'
validating file 'incidents/kul_20220621.yml'
parsing file 'incidents/vub_20220621.yml'
validating file 'incidents/vub_20220621.yml'
parsing file 'incidents/antwerp_20220710.yml'
### error: time data '' does not match format '%Y-%m-%d %H:%M:%S %z'
```

This also happens if I just copy one of the existing incidents.

Any ideas?

**Comment by backelj** [comment]
@gjbex As said, I just copied incidents/kul_20220621.yml to incidents/antwerp_20220710.yml, the files are identical...

**Comment by RVerschoren** [comment]
The file was not submitted to git, so the call to `last_updated = get_modification_date(...)` in `parse_file` `scripts/incident_parser.py` failed for that `incident_file_name`.

Perhaps we can introduce a fall-back to the file system modification date when the git call fails?

**Comment by gjbex** [comment]
@backelj Indeed, that is exactly what I've done in the last commit ;)

Thanks for spotting this, I didn't do any local verification recently, so I never noticed that adding the modification time logic would fail on files that were not committed.
